image: Visual Studio 2017

platform: x64
configuration: Release

version: ci.{build}

before_build:
  - COPY .ci\VS2017.props .\Build.props

build:
  parallel: false
  project: QuantLib.sln
  verbosity: normal
